#!/bin/bash
set -eo pipefail
ENV_FILE="../../.env"
set -a; [ -f $ENV_FILE ] && . $ENV_FILE; set +a
if [[ -z $LOCAL_BASE_URL ]]; then
  if [[ -s $ENV_FILE ]]; then
    printf "\n" >> $ENV_FILE
  fi
  LOCAL_BASE_URL=$(lando info -p $[0].urls.$[1] | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g')
  printf "LOCAL_BASE_URL=${LOCAL_BASE_URL}" >> $ENV_FILE
fi
export CYPRESS_URL=$LOCAL_BASE_URL
yarn run cypress open
