#!/bin/bash

set -eo pipefail

# Build Lean Theme assets (if composer exists).
LT_COMPOSER=web/wp-content/themes/lean-theme/composer.json

if [ -f "$LT_COMPOSER" ]; then
  echo "Lean Theme is installed"
  composer -n build-theme-assets
else
  echo "Lean Theme is not installed yet"
fi