#!/bin/bash

set -eo pipefail

# Build Lean Theme assets (if directory exists).
LEANTHEME=web/wp-content/themes/lean-theme

if [ -d "$LEANTHEME" ]; then
  echo "Lean Theme is installed"
  composer -n build-theme-assets
else
  echo "Lean Theme is not installed yet"
fi
