#!/bin/bash

set -eo pipefail

#
# This script runs static tests which
# can be performed without code execution.
#
# Some example are code sniffing and unit testing
#

# Run composer install to get the vendor directory
composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

# Run unit tests
composer -n unit-test

# Delete and reset the web directory
# This is necessary so that third-party
# dependencies are not tested
git clean -fdX web

# Lint php code for syntax errors
composer -n lint

# Check Theme coding standards
FILE=./web/wp-content/themes/lean-theme/composer.json
if [[ -f "$FILE" ]]
then
    # Run Lean Theme linter
    cd web/wp-content/themes/lean-theme
    composer install --no-ansi --no-interaction --optimize-autoloader --no-progress
    composer -n lint
else
    # Run default linter
    composer -n code-sniff
fi